name: Create a release

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/flutter_analyze_and_test.yml
  build:
    name: Build
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !contains(join(github.event.commits.*.message,';'), '#skip') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
      - name: build apk
        run: flutter build apk --release
      - name: extract version number
        id: yq
        uses: mikefarah/yq@v4.40.5
        with:
          cmd: yq -r '.version' 'pubspec.yaml'
      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: ${{ steps.yq.outputs.result }}
      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: ${{ steps.yq.outputs.result }}
          bodyFile: "${{ steps.yq.outputs.result }}.md"
